### ISSUE TITLE
training

### ISSUE THREAD

**Issue by Brown2Wang** [yfeng95/DECA#163]
Traceback (most recent call last):
  File "main_train.py", line 46, in <module>
    main(cfg)
  File "main_train.py", line 38, in main
    trainer.fit()
  File "/mnt/vdh/img_generator/wcw_dev/code/DECA/decalib/trainer.py", line 403, in fit
    shape_images = self.deca.render.render_shape(opdict['verts'][visind], opdict['trans_verts'][visind])
RuntimeError: CUDA error: device-side assert triggered

**Comment by anushka17agarwal** [comment]
@Brown2Wang I have the same error, how did you solve it?
